function A_a = A_a_matrix(in1,fm,fa)
%A_a_matrix
%    A_a = A_a_matrix(IN1,FM,FA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    16-Jan-2024 10:23:33

theta = in1(:,4);
A_a = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,fm.*sin(theta).*(-5.0e-4),0.0,0.0,0.0,1.0,0.0,-3.0./4.0e+1,0.0,0.0,0.0,0.0,1.0,0.0,-3.0./1.0e+3],[6,6]);
end
