function Bk = B_matrix(in1,fm,fa)
%B_matrix
%    Bk = B_matrix(IN1,FM,FA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    15-Jan-2024 15:00:08

theta = in1(:,2);
Bk = reshape([0.0,0.0,cos(theta)./2.0e+3,0.0,0.0,0.0,0.0,1.0./2.5e+2],[4,2]);
end
