function B_a = B_a_matrix(in1,fm,fa)
%B_a_matrix
%    B_a = B_a_matrix(IN1,FM,FA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    22-Jan-2024 09:51:44

theta = in1(:,4);
B_a = reshape([0.0,0.0,0.0,0.0,cos(theta)./2.0e+3,0.0,0.0,0.0,0.0,0.0,0.0,1.0./2.5e+2],[6,2]);
end
