function A = A_matrix(in1,fm,fa)
%A_matrix
%    A = A_matrix(IN1,FM,FA)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    17-Jan-2024 11:05:21

theta = in1(:,2);
A = reshape([0.0,0.0,0.0,0.0,0.0,0.0,fm.*sin(theta).*(-5.0e-4),0.0,1.0,0.0,-3.0./4.0e+1,0.0,0.0,1.0,0.0,-3.0./1.0e+3],[4,4]);
end
